# 实例
load_speed: 81.27 # 加载速度 任务从硬盘加载到内存的速度 MB/s
suspend_speed: 63.67 # 挂起速度 任务从内存挂起到硬盘的速度 MB/s
rental_time: 1.0 # 一次租赁操作所续租的时间

# Downey's speedup model
A: 64
sigma: 0.0

# 环境
job_number: 100
submit_speed: 20 # 任务提交速度 在一个小时内提交的任务数量 即任务提交间隔分布中的 lambda
job_length_distribution:
  name: uniform # 均匀分布 uniform 正态分布 normal
  parameters: [0.5, 2] # 任务长度分布的参数 均匀分布 [min, max] 正态分布 [mean, std]
job_type_ratio: 0.5 # Moldable 类型的任务占全部任务的比例
